[package]
name = "superspace-extension"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
superspace-extensions = { path = "../../crates/extensions" }

[lints]
workspace = true
