[package]
name = "superspace"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
desktop = ["superspace-ui/desktop"]

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
superspace-core = { path = "../../crates/core" }
superspace-files = { path = "../../crates/files" }
superspace-network = { path = "../../crates/network" }
superspace-platform = { path = "../../crates/platform" }
superspace-productivity = { path = "../../crates/productivity" }
superspace-storage = { path = "../../crates/storage" }
superspace-sync = { path = "../../crates/sync" }
superspace-ui = { path = "../../crates/ui" }
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
