[package]
name = "superspace"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
desktop = ["superspace-ui/desktop"]

[dependencies]
anyhow.workspace = true
superspace-core = { path = "../../crates/core" }
superspace-platform = { path = "../../crates/platform" }
superspace-ui = { path = "../../crates/ui" }

[lints]
workspace = true
