[package]
name = "superspace-calculator"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
chrono-tz.workspace = true
rust_decimal.workspace = true
thiserror.workspace = true

[lints]
workspace = true
